<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="VENKAT-PC" failures="0" tests="1" name="usingFrameWork" time="111.039" errors="0" timestamp="2020-11-19T18:42:17 AST">
  <testcase classname="leave.Sigletwo" name="@AfterTest exit" time="0.001">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at leave.Sigletwo.exit(Sigletwo.java:80)
at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.base/java.lang.Thread.run(Unknown Source)
... Removed 15 stack frames]]>
    </failure>
  </testcase> <!-- @AfterTest exit -->
  <testcase classname="leave.LeaveApply" name="landingOnLeavePage" time="75.234"/>
</testsuite> <!-- usingFrameWork -->
